---
title: "Assignment1"
author: "Samuel Kigamba"
date: "Sep 1, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### DATA 607: Assignment1 – Loading Data into a Data Frame - Mushroom Data

###Load data into a data frame named MD.

MD<- read.table("https://archive.ics.uci.edu/ml/machine-learning-databases/mushroom/agaricus-lepiota.data", header = F, sep = ",")

###Review the column titles.
names(MD)

###Review the data frame structure as well as a summary of the data items.
summary(MD)

###Review first 5 rows of the data frame
head(MD, 5)

###Review last 5 rows in the data frame to confirm that the data has loaded correctly.
tail(MD, 5)

###Rename the columns (note the default naming of columns is V1, V2,....., V23)
names(MD) <- c("classes", "cap-shape", "cap-surface", "cap-color", "bruises?", "odor", "gill-attachment", "gill-spacing", "gill-size", "gill-color", "stalk-shape", "stalk-root", "stalk-surface-above-ring", "stalk-surface-below-ring", "stalk-color-above-ring", "stalk-color-below-ring", "veil-type", "veil-color", "ring-number", "ring-type", "spore-print-color", "population", "habitat")

###Confirm name change
names(MD)

###Replace abbreviations used in column named classes
levels(MD$classes) [levels(MD$classes)=="p"] <- "poisonous"
levels(MD$classes) [levels(MD$classes)=="e"] <- "edible"



